<?php

date_default_timezone_set('UTC');

$LIB_DIR = realpath(dirname(__FILE__));
$APP_DIR = dirname($LIB_DIR);
$HTDOCS_DIR = $APP_DIR . '/htdocs';
$HTTPD_CONF = '../conf/httpd.conf';


// work from lib directory
chdir($LIB_DIR);

// add lib directory to include path
$include_path = get_include_path() . PATH_SEPARATOR . $LIB_DIR;


// write apache configuration
file_put_contents($HTTPD_CONF, '
	## autogenerated at ' . date('r') . '

	# add template lib directory to include path
	php_value include_path "' . $include_path . '"

	# template alias for css/js/images
	Alias /template ' . $HTDOCS_DIR . '

	# permissions for template directory
	<Location /template>
		Order Allow,Deny
		Allow From all
	</Location>
');
